languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "public/lib/css/bootstrap.css"
- "public/lib/css/bootstrap.min.css"
- "public/lib/css/mdb.css"
- "public/lib/css/mdb.min.css"
- "public/lib/css/style.css"
- "public/lib/js/bootstrap.js"
- "public/lib/js/bootstrap.min.js"
- "public/lib/js/jquery-2.2.3.js"
- "public/lib/js/jquery-2.2.3.min.js"
- "public/lib/js/mdb.js"
- "public/lib/js/mdb.min.js"
- "public/lib/js/tether.js"
- "public/lib/js/tether.min.js"
- "node_modules/**"